### ISSUE TITLE
Getting started guide?

### ISSUE THREAD

**Issue by stahnma** [dippnerd/Dashboard#1]
Hi, I found this link somewhere in /r/homeautomation and thought it looked interesting. I am a developer, however javascript and it's ecosystem certainly are not my strong suit. What's the magic incantation to get this started? 

The project doesn't have a packages.json file which I'd expect for something using node/npm, but maybe there's something newer/cooler I don't even know about afoot. 

So, basically what's the right way to get this serving out content? I might try to hack on it. I have wemo devices, alexa, raspberry pis, etc. 

:clinking_glasses:

**Comment by dippnerd** [comment]
Apologies, I hadn't finished scrubbing some of my files so they didn't all get uploaded, but if you clone the repo now you should have everything including the package.json

All you need to change to get started is change the key on line 19 to your own [Forecast.io API key](https://darksky.net/dev/) and your latitude/longitude in the forecast.get on line 26. 

At the moment only the views for weather and music are posted (music comes from a [separate project](https://github.com/Siddharth11/iTunes-Remote/), so you'll need to update the URL that points to, but the longterm goal is to make this whole piece modular. 

The lack of views for lights, devices etc is because too much of that code is specific to my setup atm, I want to break that into something more generic first. 

Let me know if you run into any trouble, now that the holidays are over I should have more time to work on this finally.
